// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForWebDevelopment12345',
    appId: '1:65554130864:web:1234567890abcdef',
    messagingSenderId: '65554130864',
    projectId: 'kinetic-fusion-app',
    authDomain: 'kinetic-fusion-app.firebaseapp.com',
    storageBucket: 'kinetic-fusion-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForAndroidDevelopment12345',
    appId: '1:65554130864:android:1234567890abcdef',
    messagingSenderId: '65554130864',
    projectId: 'kinetic-fusion-app',
    storageBucket: 'kinetic-fusion-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForiOSDevelopment12345',
    appId: '1:65554130864:ios:1234567890abcdef',
    messagingSenderId: '65554130864',
    projectId: 'kinetic-fusion-app',
    storageBucket: 'kinetic-fusion-app.appspot.com',
    iosBundleId: 'com.kineticfusion.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForMacOSDevelopment12345',
    appId: '1:65554130864:ios:1234567890abcdef',
    messagingSenderId: '65554130864',
    projectId: 'kinetic-fusion-app',
    storageBucket: 'kinetic-fusion-app.appspot.com',
    iosBundleId: 'com.kineticfusion.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForWindowsDevelopment12345',
    appId: '1:65554130864:web:1234567890abcdef',
    messagingSenderId: '65554130864',
    projectId: 'kinetic-fusion-app',
    storageBucket: 'kinetic-fusion-app.appspot.com',
  );
}
